image: misterio92/ci-php-node:latest

variables:
    WORK_DIR: ${CI_PROJECT_NAME}
    BRANCH: ${CI_COMMIT_REF_NAME}
    REPO: https://gitlab.com/l4pc/madera-api.git
    SSL_PASSPHRASE: ${SSL_PASSPHRASE}
  
stages:
    - test
    - deploy

# Run our tests
test:
    stage: test
    environment: 
        name: Test
    services:
        - mariadb:10.1
    variables:
          # Configure mysql service (https://hub.docker.com/_/mysql/)
          MYSQL_ROOT_PASSWORD: test

    # Select what we should cache between builds
    cache:
        paths:
            - vendor/
    before_script:
        - npm install newman -g
    script:
        - composer install
        - php bin/console doctrine:database:create --env=test
        - php bin/console doctrine:schema:update --force --env=test
        - php bin/console doctrine:fixtures:load --env=test
        - php bin/console cache:clear --env=test
        - mkdir -p config/jwt
        - openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:e592d5752bcce9d9fb84e3fd679dc9fb
        - openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:e592d5752bcce9d9fb84e3fd679dc9fb
        # - newman run ./tests/postman_collection.json --environment ./tests/postman_environment.json -r cli

deploy:
    stage: deploy
    before_script:
        - apt-get update -qq
        # Setup SSH deploy keys
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - mkdir -p ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    script: 
        - ssh root@51.77.192.18 'rm -rf /var/www/trodix.com/api'
        - ls -lah
        - pwd
        - ssh root@51.77.192.18 'cd /var/www/trodix.com; mkdir api;'
        - rsync -r ./ root@51.77.192.18:/var/www/trodix.com/api
        - ssh root@51.77.192.18 'cd /var/www/trodix.com/api/; ls -lah; export APP_ENV=prod; php composer.phar install --no-dev --optimize-autoloader; php composer.phar dump-env prod'
        - ssh root@51.77.192.18 'cd /var/www/trodix.com/api/; mkdir -p config/jwt; openssl genpkey -out config/jwt/private.pem -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096 -pass pass:e592d5752bcce9d9fb84e3fd679dc9fb; openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -pubout -passin pass:e592d5752bcce9d9fb84e3fd679dc9fb;'
    only: 
        - develop
        - master


