# register:
#     path: /api/register
#     controller: App\Controller\AuthController::register
#     methods: POST

# api_login:
#     path: /api/login
#     controller: App\Controller\AuthController::login
#     methods: [GET, POST]

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /v1
        permanent: true

api_login_check:
    path: /v1/login_check

gesdinet_jwt_refresh_token:
    path: /v1/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh