# register:
#     path: /api/register
#     controller: App\Controller\AuthController::register
#     methods: POST

# api_login:
#     path: /api/login
#     controller: App\Controller\AuthController::login
#     methods: [GET, POST]
    
api_login_check:
    path: /api/login_check
    methods: POST